import { useContext } from 'react';
import { Typography } from '@mui/material';
import { DataContext } from '../context';
import { WARNING } from '../types';

const LABELS: Record<WARNING, string> = {
  [WARNING.CUSTOM_MERGE]: 'Custom Merge',
  [WARNING.NON_REDIRECT_WIKIDATA_ERROR]: 'Non-Redirect Wikidata Error',
};

export const Warnings: React.FC = () => {
  const data = useContext(DataContext);
  const { warnings } = data.__hack__;

  return (
    <article style={{ margin: 16 }}>
      This page contains internal warnings generated by the conflation process.
      {Object.entries(LABELS).map(([key, label]) => {
        return (
          <div key={key}>
            <Typography variant="h5">{label}</Typography>
            <ul>
              {warnings[key as never as WARNING]?.map((warning) => {
                return <li key={warning}>{warning}</li>;
              })}
            </ul>
          </div>
        );
      })}
    </article>
  );
};
